name: Docs

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Zig
        uses: korandoru/setup-zig@v1
        with:
          zig-version: master

      - name: Generate docs
        run: zig test -femit-docs=./docs src/lib.zig
